version: "3.1"

services:
  front:
    container_name: front-part-for-test-task
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: npm run start
    tty: true
    volumes:
      - .:/app
      - /node_modules
    ports:
      - 4200:4200
    environment:
      - PORT=4200
