version: '3.1'

services:
  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test_task
      MYSQL_USER: test
    ports:
      - 3307:3306
